"""added table to the sermon

Revision ID: 29eff60fdc49
Revises: 3225beeba12c
Create Date: 2025-07-23 12:02:21.676751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29eff60fdc49'
down_revision = '3225beeba12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sermons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('preacher', sa.String(length=150), nullable=False),
    sa.Column('date_preached', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audio_file', sa.String(length=255), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_sermons_admin_id_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sermons'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sermons')
    # ### end Alembic commands ###
