"""postgresql

Revision ID: 3225beeba12c
Revises: 
Create Date: 2025-07-22 08:59:49.426898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3225beeba12c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_email')),
    sa.UniqueConstraint('username', name=op.f('uq_admin_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
